server :
  port : 8083
  ssl:
    key-store: classpath:www.xrcdx.com.pfx
    key-store-type: PKCS12
    key-store-password: dp17dt7l
spring :
  datasource:

    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uet?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: xtgm97239
    spring:
      datasource:
        hikari:
           max-lifetime : 120000
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB  # 设置多个文件大小为100MB
  #devtools:
    #restart:
      #enabled: true
      #additional-paths: src/main/java
     # exclude: static/** #没有静态资源写不写都可以

mybatis:
  mapper-locations: classpath:mapper/*.xml





